std_msgs/Header header

float64 outer_fl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 center_fl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 inner_fl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 outer_fr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 center_fr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 inner_fr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
