std_msgs/Header header

float64 outer_rl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 center_rl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 inner_rl  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 outer_rr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 center_rr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
float64 inner_rr  # 0,0 - 102,3°C, Range: -, Scale: 0.1, Offset: 0
