std_msgs/Header header

#Range: 0..1 (0..100000 Pa)
float64 cba_min_pressure_fl_pa

#Range: 0..30 (5000000..20000000 Pa)
float64 cba_max_pressure_fl_pa

#Range: 0..1 (0..100000 Pa)
float64 cba_min_pressure_fr_pa

#Range: 0..30 (5000000..20000000 Pa)
float64 cba_max_pressure_fr_pa

#Range: 0..1 (0..100000 Pa)
float64 cba_min_pressure_rl_pa

#Range: 0..30 (5000000..20000000 Pa)
float64 cba_max_pressure_rl_pa

#Range: 0..1 (0..100000 Pa)
float64 cba_min_pressure_rr_pa

#Range: 0..30 (5000000..20000000 Pa)
float64 cba_max_pressure_rr_pa

#Range: 0..100 (0..100 %)
float64 ice_max_throttle

#Range: 0..100 (0..100 %)
float64 ice_min_throttle

