std_msgs/Header header

float64 cba_actual_pressure_rl_pa  # Range: 0..4095 (0..40950000 Pa), Scale: 10000, Offset: 0
float64 cba_actual_pressure_rl  # Range: 0..2000 (0..100 %), Scale: 0.05, Offset: 0
float64 cba_target_pressure_rl_ack  # Range: 0..2000 (0..100 %), Scale: 0.05, Offset: 0
float64 cba_actual_current_rl_a  # Range: 0..1000 (-50..50 A), Scale: 0.1, Offset: -50
float64 cba_voltage_rl_v  # Range: 0..255 (0..102 V), Scale: 0.4, Offset: 0
