std_msgs/Header header
            
#Range: 0..120 (0..12 bar)
float64 emb_line_pressure_bar
            
#Range: 0..120 (0..12 bar)
float64 emb_tank_pressure_bar

#Range: 0..1023 (0..1023 uint)
uint16 em_status

#Range: 0..1023 (0..102.3 m/s)
float64 hl_stop_deceleration_1

#Range: 0..1023 (0..102.3 m/s)
float64 hl_stop_deceleration_2
            
#Range: 0..1023 (0..102.3 s)
float64 hl_stop_time_to_dec_1

#Range: 0..1023 (0..102.3 s)
float64 hl_stop_time_to_dec_2

