std_msgs/Header header

uint8 cba_fl_sw_minor_version  # Range: 0..127 (0..127 uint), Scale: 1, Offset: 0
uint8 cba_fl_sw_major_version  # Range: 0..31 (0..31 uint), Scale: 1, Offset: 0
uint16 cba_fl_sw_build_version  # Range: 0..1023 (0..1023 uint), Scale: 1, Offset: 0
uint8 cba_fr_sw_minor_version  # Range: 0..127 (0..127 uint), Scale: 1, Offset: 0
uint8 cba_fr_sw_major_version  # Range: 0..31 (0..31 uint), Scale: 1, Offset: 0
uint16 cba_fr_sw_build_version  # Range: 0..1023 (0..1023 uint), Scale: 1, Offset: 0
