std_msgs/Header header

# Software version information for BSU and other components
uint8 bsu_sw_minor_version          # BSU Software Minor Version (0..127)
uint8 bsu_sw_major_version          # BSU Software Major Version (0..31)
uint16 bsu_sw_build_version         # BSU Software Build Version (0..1023)
uint8 psa_sw_minor_version          # PSA Software Minor Version (0..127)
uint8 psa_sw_major_version          # PSA Software Major Version (0..31)
uint16 psa_sw_build_version         # PSA Software Build Version (0..1023)
uint8 pdu12_sw_version              # PDU12 Software Version (0..255)
uint8 pdu48_sw_version              # PDU48 Software Version (0..255)