std_msgs/Header header

uint8 bsu_sw_minor_version  # Range: 0..127 (0..127 uint), Scale: 1, Offset: 0
uint8 bsu_sw_major_version  # Range: 0..31 (0..31 uint), Scale: 1, Offset: 0
uint16 bsu_sw_build_version  # Range: 0..1023 (0..1023 uint), Scale: 1, Offset: 0
uint8 psa_sw_minor_version  # Range: 0..127 (0..127 uint), Scale: 1, Offset: 0
uint8 psa_sw_major_version  # Range: 0..31 (0..31 uint), Scale: 1, Offset: 0
uint16 psa_sw_build_version  # Range: 0..1023 (0..1023 uint), Scale: 1, Offset: 0
uint8 pdu1_sw_version  # Range: 0..255 (0..255 uint), Scale: 1, Offset: 0
uint8 pdu2_sw_version  # Range: 0..255 (0..255 uint), Scale: 1, Offset: 0
